// ============================================================
// GEOTHERMAL COMMUNITY HUB - Mock Data (Simulasi/Demo)
// âš ï¸ SEMUA DATA ADALAH SIMULASI UNTUK KEPERLUAN DEMO MVP
// ============================================================

import type {
  Industry,
  CommunityMember,
  CommunityAgent,
  Job,
  Internship,
  Training,
  Supplier,
  CommunityProgram,
  DirectUseOpportunity,
  Application,
  ESGMetric,
  Notification,
  MatchResult,
} from '@/types';

// --- Industries ---
export const mockIndustries: Industry[] = [
  {
    id: 'ind-001',
    userId: 'user-ind-001',
    companyName: 'PT Geothermal Demo',
    location: 'Kabupaten Demo Selatan',
    operatingArea: 'Area Operasi Demo Alpha',
    description: 'Operator geothermal terkemuka di wilayah demo dengan kapasitas pembangkitan listrik dan potensi pemanfaatan langsung panas bumi.',
    contactPerson: 'Budi Santoso',
    contactEmail: 'budi@geothermaldemo.id',
    verified: true,
    activeJobs: 8,
    activePrograms: 5,
    createdAt: '2024-01-15',
  },
  {
    id: 'ind-002',
    userId: 'user-ind-002',
    companyName: 'PT Energi Bumi Nusantara',
    location: 'Kabupaten Demo Utara',
    operatingArea: 'Area Operasi Demo Beta',
    description: 'Perusahaan energi terbarukan dengan fokus pada pengembangan geothermal dan program pemberdayaan komunitas lokal.',
    contactPerson: 'Sari Dewi',
    contactEmail: 'sari@ebn-demo.id',
    verified: true,
    activeJobs: 5,
    activePrograms: 3,
    createdAt: '2024-02-20',
  },
];

// --- Community Members ---
export const mockCommunityMembers: CommunityMember[] = [
  {
    id: 'mem-001',
    userId: 'user-mem-001',
    name: 'Andi Pratama',
    location: 'Desa Demo Jaya',
    district: 'Kecamatan Demo Selatan',
    education: 'sma',
    skills: ['IoT', 'Arduino', 'Networking', 'Electrical'],
    interests: ['Teknologi', 'Energi Terbarukan'],
    experience: [
      {
        title: 'Teknisi Listrik',
        organization: 'Usaha Lokal Demo',
        duration: '2 tahun',
        description: 'Pemasangan dan perawatan instalasi listrik',
      },
    ],
    employmentStatus: 'unemployed',
    profileCompletion: 85,
    matchScore: 92,
    status: 'available',
    agentId: 'agt-001',
    createdAt: '2024-03-10',
  },
  {
    id: 'mem-002',
    userId: 'user-mem-002',
    name: 'Siti Rahayu',
    location: 'Desa Demo Makmur',
    district: 'Kecamatan Demo Tengah',
    education: 'd3',
    skills: ['Agriculture', 'Aquaculture', 'Business'],
    interests: ['Pertanian', 'Usaha Mandiri', 'Lingkungan'],
    experience: [
      {
        title: 'Petani',
        organization: 'Kelompok Tani Demo',
        duration: '5 tahun',
        description: 'Budidaya sayuran dan ikan air tawar',
      },
    ],
    employmentStatus: 'entrepreneur',
    businessField: 'Pertanian & Perikanan',
    profileCompletion: 90,
    matchScore: 87,
    status: 'available',
    agentId: 'agt-001',
    createdAt: '2024-03-15',
  },
  {
    id: 'mem-003',
    userId: 'user-mem-003',
    name: 'Dedi Kurniawan',
    location: 'Desa Demo Sejahtera',
    district: 'Kecamatan Demo Utara',
    education: 's1',
    skills: ['Electrical', 'Maintenance', 'IoT', 'Networking'],
    interests: ['Teknik', 'Industri', 'Teknologi'],
    experience: [
      {
        title: 'Teknisi',
        organization: 'Bengkel Elektronik Demo',
        duration: '3 tahun',
        description: 'Perawatan dan perbaikan peralatan elektronik',
      },
    ],
    employmentStatus: 'unemployed',
    profileCompletion: 78,
    matchScore: 88,
    status: 'available',
    agentId: 'agt-002',
    createdAt: '2024-04-01',
  },
  {
    id: 'mem-004',
    userId: 'user-mem-004',
    name: 'Rini Wulandari',
    location: 'Desa Demo Bahagia',
    district: 'Kecamatan Demo Barat',
    education: 'sma',
    skills: ['Hospitality', 'Business', 'Tourism'],
    interests: ['Pariwisata', 'Usaha', 'Kerajinan'],
    experience: [],
    employmentStatus: 'student',
    profileCompletion: 65,
    matchScore: 75,
    status: 'training',
    agentId: 'agt-001',
    createdAt: '2024-04-10',
  },
  {
    id: 'mem-005',
    userId: 'user-mem-005',
    name: 'Hendra Setiawan',
    location: 'Desa Demo Maju',
    district: 'Kecamatan Demo Selatan',
    education: 'smp',
    skills: ['Construction', 'Agriculture'],
    interests: ['Pertanian', 'Konstruksi'],
    experience: [
      {
        title: 'Buruh Bangunan',
        organization: 'Proyek Demo',
        duration: '4 tahun',
        description: 'Konstruksi bangunan dan infrastruktur',
      },
    ],
    employmentStatus: 'unemployed',
    profileCompletion: 55,
    matchScore: 70,
    status: 'available',
    agentId: 'agt-002',
    createdAt: '2024-04-20',
  },
  {
    id: 'mem-006',
    userId: 'user-mem-006',
    name: 'Maya Anggraini',
    location: 'Desa Demo Ceria',
    district: 'Kecamatan Demo Tengah',
    education: 's1',
    skills: ['Business', 'Hospitality', 'Food Processing'],
    interests: ['UMKM', 'Kuliner', 'Pariwisata'],
    experience: [
      {
        title: 'Pengelola UMKM',
        organization: 'Warung Demo',
        duration: '2 tahun',
        description: 'Pengelolaan usaha kuliner lokal',
      },
    ],
    employmentStatus: 'entrepreneur',
    businessField: 'Kuliner & UMKM',
    profileCompletion: 88,
    matchScore: 82,
    status: 'available',
    agentId: 'agt-001',
    createdAt: '2024-05-01',
  },
];

// --- Community Agents ---
export const mockCommunityAgents: CommunityAgent[] = [
  {
    id: 'agt-001',
    userId: 'user-agt-001',
    name: 'Pak Rahman',
    location: 'Kecamatan Demo Selatan',
    district: 'Kabupaten Demo',
    totalMembers: 45,
    activePlacements: 12,
    createdAt: '2024-01-20',
  },
  {
    id: 'agt-002',
    userId: 'user-agt-002',
    name: 'Bu Fatimah',
    location: 'Kecamatan Demo Utara',
    district: 'Kabupaten Demo',
    totalMembers: 38,
    activePlacements: 8,
    createdAt: '2024-02-05',
  },
];

// --- Jobs ---
export const mockJobs: Job[] = [
  {
    id: 'job-001',
    industryId: 'ind-001',
    industryName: 'PT Geothermal Demo',
    title: 'IoT Technician',
    location: 'Area Operasi Demo Alpha',
    type: 'full-time',
    skills: ['IoT', 'Arduino', 'Networking', 'Electrical'],
    description: 'Bertanggung jawab untuk pemasangan, konfigurasi, dan pemeliharaan perangkat IoT di area operasi geothermal. Kandidat akan bekerja dalam tim monitoring sistem.',
    requirements: [
      'Pendidikan minimal SMA/SMK jurusan Teknik Elektro/Elektronika',
      'Memahami dasar-dasar IoT dan mikrokontroler',
      'Berpengalaman dengan Arduino atau Raspberry Pi',
      'Mampu bekerja dalam tim',
      'Diutamakan dari kabupaten setempat',
    ],
    quota: 5,
    applicants: 12,
    status: 'open',
    deadline: '2024-12-31',
    matchedCandidates: 12,
    bestMatch: 92,
    createdAt: '2024-10-01',
  },
  {
    id: 'job-002',
    industryId: 'ind-001',
    industryName: 'PT Geothermal Demo',
    title: 'Teknisi Mekanik Senior',
    location: 'Area Operasi Demo Alpha',
    type: 'full-time',
    skills: ['Mechanical', 'Maintenance', 'Welding'],
    description: 'Melakukan perawatan dan perbaikan peralatan mekanik di fasilitas geothermal. Bertanggung jawab atas inspeksi rutin dan penanganan kerusakan.',
    requirements: [
      'Pendidikan minimal D3 Teknik Mesin',
      'Pengalaman minimal 3 tahun di bidang maintenance industri',
      'Memiliki sertifikat K3 umum',
      'Bersedia ditempatkan di lapangan',
    ],
    quota: 3,
    applicants: 7,
    status: 'open',
    deadline: '2024-12-15',
    matchedCandidates: 5,
    bestMatch: 78,
    createdAt: '2024-10-05',
  },
  {
    id: 'job-003',
    industryId: 'ind-002',
    industryName: 'PT Energi Bumi Nusantara',
    title: 'Community Liaison Officer',
    location: 'Area Operasi Demo Beta',
    type: 'full-time',
    skills: ['Communication', 'Community Development', 'Bahasa Indonesia'],
    description: 'Menjadi penghubung antara perusahaan dan komunitas lokal. Mengelola program CSR dan community engagement.',
    requirements: [
      'Pendidikan minimal S1 semua jurusan',
      'Memiliki kemampuan komunikasi yang baik',
      'Berpengalaman di bidang community development',
      'Berasal dari daerah operasi atau sekitarnya',
    ],
    quota: 2,
    applicants: 15,
    status: 'open',
    deadline: '2024-11-30',
    matchedCandidates: 8,
    bestMatch: 85,
    createdAt: '2024-10-08',
  },
  {
    id: 'job-004',
    industryId: 'ind-001',
    industryName: 'PT Geothermal Demo',
    title: 'Operator SCADA',
    location: 'Area Operasi Demo Alpha',
    type: 'full-time',
    skills: ['SCADA', 'Electrical', 'Monitoring'],
    description: 'Mengoperasikan sistem SCADA untuk pemantauan dan pengendalian proses geothermal.',
    requirements: [
      'Pendidikan minimal D3 Teknik Elektro',
      'Familiar dengan sistem SCADA/DCS',
      'Bersedia bekerja shift',
    ],
    quota: 4,
    applicants: 9,
    status: 'open',
    deadline: '2024-12-20',
    matchedCandidates: 6,
    bestMatch: 80,
    createdAt: '2024-10-10',
  },
  {
    id: 'job-005',
    industryId: 'ind-002',
    industryName: 'PT Energi Bumi Nusantara',
    title: 'Staf Administrasi',
    location: 'Kantor Demo',
    type: 'full-time',
    skills: ['Administration', 'Microsoft Office', 'Communication'],
    description: 'Mendukung operasional administrasi dan pengelolaan dokumen perusahaan.',
    requirements: [
      'Pendidikan minimal D3 Administrasi',
      'Mahir Microsoft Office',
      'Teliti dan detail-oriented',
    ],
    quota: 2,
    applicants: 20,
    status: 'open',
    deadline: '2024-11-15',
    matchedCandidates: 15,
    bestMatch: 76,
    createdAt: '2024-10-12',
  },
];

// --- Internships ---
export const mockInternships: Internship[] = [
  {
    id: 'int-001',
    industryId: 'ind-001',
    industryName: 'PT Geothermal Demo',
    title: 'Program Magang IoT & Monitoring',
    location: 'Area Operasi Demo Alpha',
    duration: '3 bulan',
    skills: ['IoT', 'Data Analysis', 'Python'],
    description: 'Program magang untuk mempelajari implementasi IoT dalam monitoring sistem geothermal. Peserta akan mendapatkan pengalaman langsung di lapangan.',
    quota: 10,
    applicants: 25,
    allowance: 'Rp 1.500.000 - Rp 2.000.000/bulan (simulasi)',
    status: 'open',
    deadline: '2024-11-30',
    startDate: '2025-01-06',
    createdAt: '2024-10-01',
  },
  {
    id: 'int-002',
    industryId: 'ind-002',
    industryName: 'PT Energi Bumi Nusantara',
    title: 'Magang Community Development',
    location: 'Kantor Demo & Lapangan',
    duration: '2 bulan',
    skills: ['Community Development', 'Data Collection', 'Reporting'],
    description: 'Pengalaman langsung dalam program community development dan ESG monitoring di industri geothermal.',
    quota: 5,
    applicants: 18,
    allowance: 'Rp 1.000.000 - Rp 1.500.000/bulan (simulasi)',
    status: 'open',
    deadline: '2024-12-15',
    startDate: '2025-02-03',
    createdAt: '2024-10-15',
  },
];

// --- Training Programs ---
export const mockTrainings: Training[] = [
  {
    id: 'trn-001',
    industryId: 'ind-001',
    industryName: 'PT Geothermal Demo',
    title: 'Pelatihan IoT Dasar untuk Teknisi Lokal',
    location: 'Balai Desa Demo & Online',
    duration: '2 minggu',
    skills: ['IoT', 'Arduino', 'Sensor'],
    description: 'Pelatihan dasar IoT khusus untuk teknisi lokal. Materi meliputi konsep dasar IoT, pemrograman Arduino, dan pemasangan sensor.',
    quota: 30,
    participants: 22,
    status: 'open',
    startDate: '2024-11-18',
    endDate: '2024-11-29',
    category: 'Teknologi',
    certificate: true,
    createdAt: '2024-10-01',
  },
  {
    id: 'trn-002',
    industryId: 'ind-001',
    industryName: 'PT Geothermal Demo',
    title: 'K3 Umum untuk Pekerja Lokal',
    location: 'Area Operasi Demo Alpha',
    duration: '3 hari',
    skills: ['K3', 'Safety', 'Emergency Response'],
    description: 'Pelatihan Keselamatan dan Kesehatan Kerja (K3) Umum yang diperlukan untuk bekerja di lingkungan industri.',
    quota: 50,
    participants: 45,
    status: 'ongoing',
    startDate: '2024-10-28',
    endDate: '2024-10-30',
    category: 'K3',
    certificate: true,
    createdAt: '2024-10-10',
  },
  {
    id: 'trn-003',
    industryId: 'ind-002',
    industryName: 'PT Energi Bumi Nusantara',
    title: 'Budidaya Ikan dengan Panas Bumi (Simulasi)',
    location: 'Desa Demo Makmur',
    duration: '1 minggu',
    skills: ['Aquaculture', 'Geothermal Direct-Use', 'Fishery'],
    description: 'Pelatihan pemanfaatan langsung panas bumi untuk budidaya ikan. Peserta akan belajar teknik aquaculture menggunakan air hangat geothermal.',
    quota: 20,
    participants: 15,
    status: 'open',
    startDate: '2024-12-02',
    endDate: '2024-12-06',
    category: 'Agro-Geothermal',
    certificate: false,
    createdAt: '2024-10-20',
  },
  {
    id: 'trn-004',
    industryId: 'ind-002',
    industryName: 'PT Energi Bumi Nusantara',
    title: 'Pelatihan UMKM Digital',
    location: 'Balai Kecamatan Demo',
    duration: '3 hari',
    skills: ['Digital Marketing', 'E-Commerce', 'Business'],
    description: 'Pelatihan digitalisasi UMKM untuk meningkatkan daya saing usaha lokal melalui pemasaran digital dan e-commerce.',
    quota: 40,
    participants: 38,
    status: 'ongoing',
    startDate: '2024-10-21',
    endDate: '2024-10-23',
    category: 'UMKM',
    certificate: false,
    createdAt: '2024-10-08',
  },
];

// --- Suppliers ---
export const mockSuppliers: Supplier[] = [
  {
    id: 'sup-001',
    name: 'CV Elektro Demo Jaya',
    category: 'Electrical',
    location: 'Kota Demo',
    district: 'Kabupaten Demo',
    products: ['Kabel Listrik', 'Panel Kontrol', 'Lampu Industri', 'Instalasi Listrik'],
    description: 'Penyedia kebutuhan elektrikal untuk industri dan komersial dengan pengalaman lebih dari 8 tahun.',
    status: 'verified',
    matchScore: 91,
    contactPerson: 'Pak Agus',
    contactPhone: '0812-DEMO-001',
    yearsActive: 8,
    createdAt: '2024-02-15',
  },
  {
    id: 'sup-002',
    name: 'UD Demo Konstruksi',
    category: 'Construction',
    location: 'Kecamatan Demo Selatan',
    district: 'Kabupaten Demo',
    products: ['Material Bangunan', 'Jasa Konstruksi', 'Renovasi', 'Sipil'],
    description: 'Kontraktor lokal berpengalaman dalam pembangunan fasilitas industri dan infrastruktur.',
    status: 'verified',
    matchScore: 85,
    contactPerson: 'Pak Joko',
    contactPhone: '0813-DEMO-002',
    yearsActive: 12,
    createdAt: '2024-03-10',
  },
  {
    id: 'sup-003',
    name: 'Kelompok Tani Demo Hijau',
    category: 'Agriculture',
    location: 'Desa Demo Makmur',
    district: 'Kabupaten Demo',
    products: ['Sayuran Segar', 'Buah Lokal', 'Katering Karyawan', 'Beras Lokal'],
    description: 'Kelompok tani yang menyediakan kebutuhan pangan segar dan katering untuk karyawan industri.',
    status: 'verified',
    matchScore: 88,
    contactPerson: 'Bu Siti',
    contactPhone: '0814-DEMO-003',
    yearsActive: 5,
    createdAt: '2024-04-01',
  },
  {
    id: 'sup-004',
    name: 'UMKM Catering Demo Rasa',
    category: 'Food',
    location: 'Kecamatan Demo Tengah',
    district: 'Kabupaten Demo',
    products: ['Katering Industri', 'Snack Box', 'Makanan Lokal', 'Air Minum Galon'],
    description: 'UMKM kuliner lokal yang melayani kebutuhan katering dan makanan untuk karyawan industri.',
    status: 'verified',
    matchScore: 82,
    contactPerson: 'Bu Maya',
    contactPhone: '0815-DEMO-004',
    yearsActive: 3,
    createdAt: '2024-04-15',
  },
  {
    id: 'sup-005',
    name: 'CV Transportasi Demo Lancar',
    category: 'Transportation',
    location: 'Kota Demo',
    district: 'Kabupaten Demo',
    products: ['Antar-Jemput Karyawan', 'Pengiriman Material', 'Sewa Kendaraan'],
    description: 'Perusahaan transportasi lokal yang melayani kebutuhan antar-jemput karyawan dan pengiriman material.',
    status: 'verified',
    matchScore: 79,
    contactPerson: 'Pak Hendra',
    contactPhone: '0816-DEMO-005',
    yearsActive: 6,
    createdAt: '2024-05-01',
  },
  {
    id: 'sup-006',
    name: 'Bengkel Demo Teknik',
    category: 'Maintenance',
    location: 'Kecamatan Demo Utara',
    district: 'Kabupaten Demo',
    products: ['Perawatan Mesin', 'Las & Fabrikasi', 'Servis Peralatan'],
    description: 'Bengkel teknik lokal yang menyediakan jasa perawatan dan perbaikan mesin industri.',
    status: 'pending',
    matchScore: 74,
    contactPerson: 'Pak Wawan',
    contactPhone: '0817-DEMO-006',
    yearsActive: 4,
    createdAt: '2024-06-01',
  },
  {
    id: 'sup-007',
    name: 'Demo IoT Solutions',
    category: 'IoT',
    location: 'Kota Demo',
    district: 'Kabupaten Demo',
    products: ['Perangkat IoT', 'Instalasi Sensor', 'Monitoring System', 'Konsultasi Teknis'],
    description: 'Startup lokal yang fokus pada solusi IoT untuk industri dan pertanian cerdas.',
    status: 'pending',
    matchScore: 70,
    contactPerson: 'Pak Dedi',
    contactPhone: '0818-DEMO-007',
    yearsActive: 2,
    createdAt: '2024-07-01',
  },
];

// --- Community Programs ---
export const mockCommunityPrograms: CommunityProgram[] = [
  {
    id: 'prg-001',
    industryId: 'ind-001',
    industryName: 'PT Geothermal Demo',
    name: 'Program Pelatihan Teknisi IoT Lokal',
    category: 'Training',
    location: 'Kecamatan Demo Selatan',
    targetParticipants: 30,
    currentParticipants: 22,
    duration: '3 bulan',
    status: 'active',
    description: 'Program pelatihan komprehensif untuk membentuk teknisi IoT dari masyarakat lokal yang siap bekerja di industri geothermal.',
    startDate: '2024-10-01',
    endDate: '2024-12-31',
    agentId: 'agt-001',
    createdAt: '2024-09-15',
  },
  {
    id: 'prg-002',
    industryId: 'ind-001',
    industryName: 'PT Geothermal Demo',
    name: 'Pengembangan Supplier Lokal',
    category: 'UMKM',
    location: 'Kabupaten Demo',
    targetParticipants: 50,
    currentParticipants: 38,
    duration: '6 bulan',
    status: 'active',
    description: 'Program pendampingan dan pengembangan kapasitas UMKM lokal agar memenuhi standar menjadi supplier industri geothermal.',
    startDate: '2024-07-01',
    endDate: '2024-12-31',
    agentId: 'agt-001',
    createdAt: '2024-06-15',
  },
  {
    id: 'prg-003',
    industryId: 'ind-002',
    industryName: 'PT Energi Bumi Nusantara',
    name: 'Demo Aquaculture Geothermal',
    category: 'Direct-use',
    location: 'Desa Demo Makmur',
    targetParticipants: 15,
    currentParticipants: 12,
    duration: '4 bulan',
    status: 'active',
    description: 'Program percontohan pemanfaatan langsung panas bumi untuk budidaya ikan air hangat, meningkatkan produktivitas dan pendapatan masyarakat.',
    startDate: '2024-09-01',
    endDate: '2024-12-31',
    agentId: 'agt-002',
    createdAt: '2024-08-20',
  },
  {
    id: 'prg-004',
    industryId: 'ind-002',
    industryName: 'PT Energi Bumi Nusantara',
    name: 'Beasiswa Pendidikan Anak Lokal',
    category: 'Education',
    location: 'Kabupaten Demo',
    targetParticipants: 25,
    currentParticipants: 25,
    duration: '1 tahun',
    status: 'active',
    description: 'Program beasiswa untuk anak-anak berprestasi dari keluarga tidak mampu di sekitar area operasi geothermal.',
    startDate: '2024-01-01',
    endDate: '2024-12-31',
    createdAt: '2023-12-01',
  },
  {
    id: 'prg-005',
    industryId: 'ind-001',
    industryName: 'PT Geothermal Demo',
    name: 'Wisata Geothermal Edukasi',
    category: 'Community Development',
    location: 'Area Operasi Demo Alpha',
    targetParticipants: 200,
    currentParticipants: 145,
    duration: 'Ongoing',
    status: 'active',
    description: 'Program wisata edukasi yang mengajak masyarakat mengenal geothermal dan potensi direct-use untuk meningkatkan ekonomi lokal.',
    startDate: '2024-04-01',
    endDate: '2024-12-31',
    createdAt: '2024-03-15',
  },
];

// --- Direct Use Opportunities ---
export const mockDirectUseOpportunities: DirectUseOpportunity[] = [
  {
    id: 'du-001',
    title: 'Budidaya Ikan Air Hangat',
    category: 'aquaculture',
    temperatureRange: '30Â°C - 40Â°C',
    description: 'Pemanfaatan air hangat dari sumber panas bumi untuk budidaya ikan tilapia, lele, dan nila dengan pertumbuhan lebih cepat.',
    benefits: [
      'Percepatan pertumbuhan ikan hingga 30% (estimasi demo)',
      'Pengurangan biaya pemanas musim dingin',
      'Potensi 2-3 siklus panen per tahun',
      'Peningkatan pendapatan masyarakat',
    ],
    requiredTemp: 35,
    requiredFlow: '10-50 L/menit',
    potentialImpact: 'Meningkatkan produksi perikanan lokal',
    status: 'in-progress',
  },
  {
    id: 'du-002',
    title: 'Pengeringan Hasil Pertanian',
    category: 'drying',
    temperatureRange: '50Â°C - 70Â°C',
    description: 'Penggunaan panas bumi untuk pengeringan hasil pertanian seperti kopi, padi, dan rempah-rempah, mengurangi ketergantungan pada cuaca.',
    benefits: [
      'Proses pengeringan lebih cepat dan konsisten',
      'Kualitas produk lebih terjaga',
      'Operasional sepanjang tahun tanpa tergantung cuaca',
      'Penghematan energi konvensional',
    ],
    requiredTemp: 60,
    requiredFlow: '20-100 L/menit',
    potentialImpact: 'Meningkatkan nilai tambah produk pertanian lokal',
    status: 'available',
  },
  {
    id: 'du-003',
    title: 'Pemanasan Fasilitas Wisata',
    category: 'tourism',
    temperatureRange: '35Â°C - 45Â°C',
    description: 'Pengembangan fasilitas wisata spa dan kolam renang menggunakan air panas geothermal secara alami.',
    benefits: [
      'Atraksi wisata unik berbasis alam',
      'Biaya operasional rendah',
      'Penciptaan lapangan kerja lokal',
      'Diversifikasi ekonomi lokal',
    ],
    requiredTemp: 40,
    requiredFlow: '50-200 L/menit',
    potentialImpact: 'Pengembangan pariwisata berbasis geothermal',
    status: 'available',
  },
  {
    id: 'du-004',
    title: 'Pertanian Greenhouse',
    category: 'agriculture',
    temperatureRange: '25Â°C - 35Â°C',
    description: 'Pemanfaatan panas bumi untuk menjaga suhu optimal greenhouse bagi tanaman sayuran dataran tinggi.',
    benefits: [
      'Produksi sayuran sepanjang tahun',
      'Perlindungan dari cuaca ekstrem',
      'Peningkatan kualitas dan kuantitas panen',
      'Ketahanan pangan lokal',
    ],
    requiredTemp: 30,
    requiredFlow: '5-20 L/menit',
    potentialImpact: 'Meningkatkan ketahanan pangan dan pendapatan petani',
    status: 'available',
  },
  {
    id: 'du-005',
    title: 'Panas Proses Industri Kecil',
    category: 'process-heat',
    temperatureRange: '60Â°C - 100Â°C',
    description: 'Penyediaan panas proses untuk industri kecil seperti pengolahan tempe, tahu, dan produk fermentasi lokal.',
    benefits: [
      'Pengurangan biaya energi UMKM',
      'Peningkatan kapasitas produksi',
      'Kualitas produk lebih konsisten',
      'Penguatan ekosistem UMKM lokal',
    ],
    requiredTemp: 80,
    requiredFlow: '30-80 L/menit',
    potentialImpact: 'Mengurangi biaya produksi UMKM lokal',
    status: 'available',
  },
];

// --- ESG Metrics ---
export const mockESGMetrics: ESGMetric[] = [
  {
    id: 'esg-001',
    industryId: 'ind-001',
    period: 'Q3 2024',
    social: {
      trainingParticipants: 145,
      localHires: 28,
      internshipParticipants: 35,
      communityParticipation: 320,
      womenParticipation: 42,
    },
    economic: {
      localSuppliers: 12,
      umkmSupported: 38,
      businessOpportunities: 15,
      estimatedLocalSpend: 850000000,
    },
    energy: {
      directUseProjects: 3,
      geothermalApplications: 5,
      energyUtilization: 68,
    },
    createdAt: '2024-10-01',
  },
];

// --- ESG Chart Data ---
export const mockESGChartData = {
  socialTrend: [
    { month: 'Jan', training: 20, hires: 5, internship: 8 },
    { month: 'Feb', training: 35, hires: 8, internship: 10 },
    { month: 'Mar', training: 45, hires: 10, internship: 12 },
    { month: 'Apr', training: 55, hires: 12, internship: 15 },
    { month: 'May', training: 70, hires: 15, internship: 18 },
    { month: 'Jun', training: 85, hires: 18, internship: 22 },
    { month: 'Jul', training: 100, hires: 20, internship: 25 },
    { month: 'Aug', training: 115, hires: 23, internship: 28 },
    { month: 'Sep', training: 145, hires: 28, internship: 35 },
  ],
  economicBreakdown: [
    { name: 'Supplier Lokal', value: 400000000, color: '#16a34a' },
    { name: 'UMKM Didukung', value: 280000000, color: '#0d9488' },
    { name: 'Peluang Bisnis', value: 170000000, color: '#0891b2' },
  ],
  directUseByCategory: [
    { name: 'Aquaculture', value: 3 },
    { name: 'Pertanian', value: 2 },
    { name: 'Pariwisata', value: 2 },
    { name: 'UMKM', value: 4 },
    { name: 'Lainnya', value: 1 },
  ],
};

// --- Notifications ---
export const mockNotifications: Notification[] = [
  {
    id: 'notif-001',
    userId: 'user-mem-001',
    title: 'Peluang Baru Tersedia',
    message: 'Anda memiliki 3 peluang kerja baru yang sesuai dengan profil Anda.',
    type: 'opportunity',
    read: false,
    createdAt: '2024-10-07T09:00:00',
    link: '/community/matching',
  },
  {
    id: 'notif-002',
    userId: 'user-mem-001',
    title: 'Lamaran Diproses',
    message: 'Lamaran Anda untuk posisi IoT Technician telah dilihat oleh PT Geothermal Demo.',
    type: 'info',
    read: false,
    createdAt: '2024-10-06T14:30:00',
    link: '/community/applications',
  },
  {
    id: 'notif-003',
    userId: 'user-mem-001',
    title: 'Training Segera Dimulai',
    message: 'Pelatihan IoT Dasar akan dimulai minggu depan. Siapkan diri Anda!',
    type: 'warning',
    read: true,
    createdAt: '2024-10-05T10:00:00',
    link: '/community/training',
  },
  {
    id: 'notif-004',
    userId: 'user-ind-001',
    title: 'Kandidat Baru Tersedia',
    message: '5 kandidat baru yang memenuhi syarat telah terdaftar di talent pool.',
    type: 'success',
    read: false,
    createdAt: '2024-10-07T08:00:00',
    link: '/industry/talent',
  },
  {
    id: 'notif-005',
    userId: 'user-ind-001',
    title: 'Supplier Baru Mendaftar',
    message: 'Demo IoT Solutions telah mendaftar sebagai supplier dan menunggu verifikasi.',
    type: 'info',
    read: false,
    createdAt: '2024-10-06T11:00:00',
    link: '/industry/suppliers',
  },
];

// --- Match Results for Community Member ---
export const mockMatchResults: MatchResult[] = [
  {
    opportunityId: 'job-001',
    opportunityTitle: 'IoT Technician',
    opportunityType: 'job',
    organizationName: 'PT Geothermal Demo',
    location: 'Area Operasi Demo Alpha',
    matchScore: 92,
    matchReasons: [
      'Skill IoT cocok 100%',
      'Lokasi dalam radius operasi',
      'Pengalaman teknik relevan',
      'Pendidikan memenuhi syarat',
    ],
    deadline: '2024-12-31',
    status: 'open',
  },
  {
    opportunityId: 'trn-001',
    opportunityTitle: 'Pelatihan IoT Dasar untuk Teknisi Lokal',
    opportunityType: 'training',
    organizationName: 'PT Geothermal Demo',
    location: 'Balai Desa Demo & Online',
    matchScore: 89,
    matchReasons: [
      'Skill teknik sesuai',
      'Minat teknologi cocok',
      'Lokasi dapat dijangkau',
    ],
    deadline: '2024-11-30',
    status: 'open',
  },
  {
    opportunityId: 'int-001',
    opportunityTitle: 'Program Magang IoT & Monitoring',
    opportunityType: 'internship',
    organizationName: 'PT Geothermal Demo',
    location: 'Area Operasi Demo Alpha',
    matchScore: 87,
    matchReasons: [
      'Profil teknik sesuai',
      'Skill IoT relevan',
      'Lokasi terjangkau',
    ],
    deadline: '2024-11-30',
    status: 'open',
  },
  {
    opportunityId: 'sup-001',
    opportunityTitle: 'Peluang Supplier Elektrikal',
    opportunityType: 'business',
    organizationName: 'PT Geothermal Demo',
    location: 'Area Operasi Demo Alpha',
    matchScore: 81,
    matchReasons: [
      'Bidang usaha relevan',
      'Lokasi sesuai',
      'Kapasitas memadai',
    ],
    status: 'available',
  },
  {
    opportunityId: 'du-001',
    opportunityTitle: 'Peluang Aquaculture Geothermal',
    opportunityType: 'direct-use',
    organizationName: 'PT Energi Bumi Nusantara',
    location: 'Area Operasi Demo Beta',
    matchScore: 78,
    matchReasons: [
      'Minat pertanian/perikanan',
      'Lokasi sesuai',
    ],
    status: 'available',
  },
];

// --- Applications ---
export const mockApplications: Application[] = [
  {
    id: 'app-001',
    memberId: 'mem-001',
    memberName: 'Andi Pratama',
    opportunityId: 'job-001',
    opportunityTitle: 'IoT Technician',
    opportunityType: 'job',
    status: 'reviewed',
    appliedAt: '2024-10-05',
    updatedAt: '2024-10-07',
  },
  {
    id: 'app-002',
    memberId: 'mem-002',
    memberName: 'Siti Rahayu',
    opportunityId: 'trn-003',
    opportunityTitle: 'Budidaya Ikan dengan Panas Bumi',
    opportunityType: 'training',
    status: 'accepted',
    appliedAt: '2024-10-03',
    updatedAt: '2024-10-06',
  },
  {
    id: 'app-003',
    memberId: 'mem-003',
    memberName: 'Dedi Kurniawan',
    opportunityId: 'job-001',
    opportunityTitle: 'IoT Technician',
    opportunityType: 'job',
    status: 'pending',
    appliedAt: '2024-10-06',
    updatedAt: '2024-10-06',
  },
  {
    id: 'app-004',
    memberId: 'mem-004',
    memberName: 'Rini Wulandari',
    opportunityId: 'trn-001',
    opportunityTitle: 'Pelatihan IoT Dasar',
    opportunityType: 'training',
    status: 'accepted',
    appliedAt: '2024-10-04',
    updatedAt: '2024-10-05',
  },
];

// --- Admin Stats ---
export const mockAdminStats = {
  totalIndustries: 2,
  totalCommunityMembers: 87,
  totalAgents: 5,
  totalOpportunities: 24,
  totalPrograms: 12,
  pendingApprovals: {
    jobs: 3,
    suppliers: 4,
    trainings: 2,
    programs: 1,
  },
  monthlyGrowth: {
    members: 15,
    opportunities: 8,
    placements: 12,
  },
};

